
export const AUTHORIZATION_S_ADMIN = "AUTHORIZATION_S_ADMIN"
export const AUTHORIZATION_SAGA = "AUTHORIZATION_SAGA"
export const AUTHORIZATION_ADMIN = "AUTHORIZATION_ADMIN"
export const LOGOUT = "LOGOUT"
export const AUTH_ERROR = "AUTH_ERROR"
export const PRELOADER = "PRELOADER"
export const REDIRECT = "REDIRECT"


