export const GET_PARTICIPANTS = "GET_PARTICIPANTS"
export const GET_PARTICIPANTS_SAGA = 'GET_PARTICIPANTS_SAGA'
export const CLEAR_PARTICIPANT_PAGE = 'CLEAR_PARTICIPANT_PAGE'
export const SET_STATUS_PARTICIPANT_SAGA = 'SET_STATUS_PARTICIPANT_SAGA'
export const SET_STATUS_PARTICIPANT = 'SET_STATUS_PARTICIPANT'
export const SET_TOTAL_PARTICIPANTS_COUNT = 'SET_TOTAL_PARTICIPANTS_COUNT'