export const GET_USERS_SAGA = 'GET_USERS_SAGA'
export const GET_USERS = "GET_USERS"
export const UPDATE_USER_SAGA = "UPDATE_USER_SAGA"
export const UPDATE_USER_STATUS = "UPDATE_USER_STATUS"
export const DEL_USER_SAGA = "DEL_USER_SAGA"
export const ADD_USER = "ADD_USER"
export const ADD_USER_SAGA = "ADD_USER_SAGA"
export const USER_ERROR = "USER_ERROR"
export const USER_PAGE_PRELOADER = "USER_PAGE_PRELOADER"
// export const REDIRECT = "REDIRECT"
export const DEL_USER = "DEL_USER"
export const USER_MODIFICATION = 'USER_MODIFICATION'
export const USER_MODIFICATION_SAGA = 'USER_MODIFICATION_SAGA'
export const CLEAR_USER_PAGE = 'CLEAR_USER_PAGE'
export const SET_COMPONENT_MODE = 'SET_COMPONENT_MODE'
export const USER_PERSONAL_PRELOADER = 'USER_PERSONAL_PRELOADER'



